<?php

return [
    'backups_path' => env('OPS_BACKUPS_PATH', storage_path('app/backups')),
    'backup_retention' => (int) env('OPS_BACKUP_RETENTION', 7),
    'backup_offsite_disk' => env('OPS_BACKUP_OFFSITE_DISK', ''),
    'backup_offsite_prefix' => env('OPS_BACKUP_OFFSITE_PREFIX', 'nema-erp/backups'),
    'backup_offsite_keep' => (int) env('OPS_BACKUP_OFFSITE_KEEP', 14),
    'web_backup_guard_enabled' => (bool) env('OPS_WEB_BACKUP_GUARD_ENABLED', true),
    'web_backup_guard_interval_minutes' => (int) env('OPS_WEB_BACKUP_GUARD_INTERVAL_MINUTES', 60),
    'web_backup_guard_max_age_hours' => (int) env('OPS_WEB_BACKUP_GUARD_MAX_AGE_HOURS', 26),
    'alert_retry_times' => (int) env('OPS_ALERT_RETRY_TIMES', 3),
    'alert_retry_backoff_ms' => (int) env('OPS_ALERT_RETRY_BACKOFF_MS', 300),
    'alert_signature_secret' => env('OPS_ALERT_SIGNATURE_SECRET'),
    'alert_circuit_failures' => (int) env('OPS_ALERT_CIRCUIT_FAILURES', 5),
    'alert_circuit_ttl_minutes' => (int) env('OPS_ALERT_CIRCUIT_TTL_MINUTES', 10),
    'core_pulse_sla_score' => (int) env('OPS_CORE_PULSE_SLA_SCORE', 75),
    'core_pulse_weights' => [
        'automation' => (int) env('OPS_CORE_PULSE_WEIGHT_AUTOMATION', 25),
        'monitoring' => (int) env('OPS_CORE_PULSE_WEIGHT_MONITORING', 25),
        'backups' => (int) env('OPS_CORE_PULSE_WEIGHT_BACKUPS', 20),
        'ecosystem' => (int) env('OPS_CORE_PULSE_WEIGHT_ECOSYSTEM', 15),
        'readiness' => (int) env('OPS_CORE_PULSE_WEIGHT_READINESS', 15),
    ],
    'log_tail' => (int) env('OPS_LOG_TAIL', 400),
    'log_window_hours' => (int) env('OPS_LOG_WINDOW_HOURS', 24),
    'failed_jobs_warning' => (int) env('OPS_FAILED_JOBS_WARNING', 1),
    'failed_jobs_fail' => (int) env('OPS_FAILED_JOBS_FAIL', 10),
    'log_warning_threshold' => (int) env('OPS_LOG_WARNING_THRESHOLD', 1),
    'log_fail_threshold' => (int) env('OPS_LOG_FAIL_THRESHOLD', 10),
];
